###test-productos

GET http://localhost:8888/index/productos HTTP/1.1

###

DELETE http://localhost:8888/index/productos/5 HTTP/1.1


###

POST http://localhost:8888/index/productos HTTP/1.1
Content-Type: application/json

{"prodDescripcion": "otrotest",
 "prodPrecio": 44444}


###

PUT http://localhost:8888/index/productos HTTP/1.1

{   "prodId": 6,
    "prodDescripcion": "producto actualizadoxxxx",
    "prodPrecio": 55555}


###test-clientes

GET http://localhost:8888/index.php/cliente HTTP/1.1

###

DELETE http://localhost:8888/index.php/cliente/27 HTTP/1.1


###

POST http://localhost:8888/index.php/cliente HTTP/1.1
Content-Type: application/json

{   "clienNombre": "el test",
    "clienDireccion": "calle falsa 123"}

###

PUT http://localhost:8888/index.php/cliente HTTP/1.1

{   "clienId": 29,
    "clienNombre": "nombre actualizadoxxxx",
    "clienDireccion": "direccion actualizada"}


###test-pedido

GET http://localhost:8888/index.php/pedidos HTTP/1.1

###

DELETE http://localhost:8888/index.php/pedidos/66 HTTP/1.1


###

POST http://localhost:8888/index.php/pedidos HTTP/1.1
Content-Type: application/json

{   "pediFecha": "2020-12-19T00:00:00",
    "pediClienId": 29 }

###

PUT http://localhost:8888/index.php/pedidos HTTP/1.1

{   "pediFecha": "2020-12-16T00:00:00",
    "pediClienId": 28,
    "pediId": 68
}


###pedido-detalle

GET http://localhost:8888/index.php/pedido-detalle HTTP/1.1

###

DELETE http://localhost:8888/index.php/pedido-detalle/55 HTTP/1.1


###

POST http://localhost:8888/index.php/pedido-detalle HTTP/1.1
Content-Type: application/json

{   "detaPediId": 65 ,
    "detaProdId": 11,
    "detaCantidad": 68,
    "detaPrecio": 1
}

###

PUT http://localhost:8888/index.php/pedido-detalle HTTP/1.1

{   "detaprodId": 11 ,
    "detaCantidad": 33,
    "detaPrecio": 22,
    "detaId":54
}

